FROM oven/bun:1.3.5 AS base
RUN apt-get update && apt-get install -y curl
WORKDIR /app

FROM base AS builder
ARG DATABASE_URL
ARG BETTER_AUTH_SECRET
ARG BETTER_AUTH_URL
ARG DRAGONFLY_URL
ARG MINIO_BUCKET
ARG MINIO_ENDPOINT
ARG MINIO_PUBLIC_ENDPOINT
ARG MINIO_ACCESS_KEY
ARG MINIO_REGION
ARG MINIO_SECRET_KEY
ARG OPENROUTER_API_KEY
ARG OPENROUTER_APP_TITLE
ARG OPENROUTER_HTTP_REFERER

ENV DATABASE_URL=$DATABASE_URL \
    BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET \
    BETTER_AUTH_URL=$BETTER_AUTH_URL \
    DRAGONFLY_URL=$DRAGONFLY_URL \
    MINIO_BUCKET=$MINIO_BUCKET \
    MINIO_ENDPOINT=$MINIO_ENDPOINT \
    MINIO_PUBLIC_ENDPOINT=$MINIO_PUBLIC_ENDPOINT \
    MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY \
    MINIO_REGION=$MINIO_REGION \
    MINIO_SECRET_KEY=$MINIO_SECRET_KEY \
    OPENROUTER_API_KEY=$OPENROUTER_API_KEY \
    OPENROUTER_APP_TITLE=$OPENROUTER_APP_TITLE \
    OPENROUTER_HTTP_REFERER=$OPENROUTER_HTTP_REFERER \
    NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    TURBO_TELEMETRY_DISABLED=1

COPY . .
RUN bun install --frozen-lockfile
RUN bun run -F @repo/db prisma generate
RUN bun x turbo build --filter=web...

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app ./

EXPOSE 3000

CMD ["./node_modules/.bin/next", "start", "apps/web"]
